### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by PabloReszczynski** [ulrikdamm/Assembler#1]
Hi! What an awesome project! I can't wait to tinker with it an make my own gameboy software! But I'm having some issues:

Doing `swift build -c release` gives this error:
```
error: package has unsupported layout; found loose source files: /Users/pablore/Documents/gameboy/Assembler/Tests/AssemblerTests.swift, /Users/pablore/Documents/gameboy/Assembler/Tests/ExpressionTests.swift, /Users/pablore/Documents/gameboy/Assembler/Tests/IntegrationTests.swift, /Users/pablore/Documents/gameboy/Assembler/Tests/LinkerTests.swift, /Users/pablore/Documents/gameboy/Assembler/Tests/ParserTests.swift, /Users/pablore/Documents/gameboy/Assembler/Tests/SpriteReaderTests.swift
```
`swift --version` yields: 
```
swift --version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9
```

Opening the project in Xcode gives a lot of Swift compiling errors, so I guess I'm using a non-compatible version of Swift. Which version are you using to build this project?

**Comment by ulrikdamm** [comment]
The project uses the newest version of Swift (4.2), so you'll need to update :)
I also just pushed a fix to the Package file, so building from the command line should work now.
