### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by rbaarda** [ulrikdamm/Assembler#2]
Hi,

I've just cloned your project and I'm afraid it doesn't build (on my system).

When running: `swift build -c release` the output is:
`Util.swift:114:10: error: cannot create a tuple with a duplicate element label`

I'm not a swift programmer, but a quick look at line 114 at Util.swift indeed reveals a duplicate label in a tuple.
A quick Google search shows that this was a bug which was fixed in Swift 5.1.
[https://bugs.swift.org/browse/SR-8974](https://bugs.swift.org/browse/SR-8974)

swift --version on my system outputs:
Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
Target: x86_64-apple-darwin19.3.0

Kind regards,

Robert Baarda

**Comment by ulrikdamm** [comment]
Thanks for the report, I just pushed a fix, should compile again now :)

**Comment by rbaarda** [comment]
Thank you for such a quick fix. I can confirm the project builds now.
